# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
# Triggers the workflow on push events to the master branch
push:
branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
build:
# The type of runner that the job will run on
runs-on: windows-latest

# Steps represent a sequence of tasks that will be executed as part of the job
steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
•  uses: actions/checkout@v2


# Setup .NET Core SDK
•  name: Setup .NET Core

uses: actions/setup-dotnet@v1
with:
dotnet-version: 3.1.301

# Setup MSBuild path
•  name: Setup MSBuild path

uses: microsoft/setup-msbuild@v1.0.2

# Build the solution with MSBuild
•  name: Build with MSBuild

run: msbuild Plain Craft Launcher.sln /p:Configuration=Release /p:Platform=x64

# Upload the exe file as a build artifact
•  name: a.exe

uses: actions/upload-artifact@v2
with:
name: exe-file
path: your-exe-file-path
